#ifndef GRAPEFRUIT_CONST_H_
#define GRAPEFRUIT_CONST_H_

#define MAX_CHAR 127
#define ALPHABET_SIZE (MAX_CHAR+1)

#define EDGE_SPECIAL_PREFIX (MAX_CHAR+1)
#define EDGE_FREE 0
#define EDGE_INPUT_BEGIN 1
#define EDGE_INPUT_END 2

#define CHAR_INPUT_BEGIN (MAX_CHAR+1 + EDGE_INPUT_BEGIN)
#define CHAR_INPUT_END (MAX_CHAR+1 + EDGE_INPUT_END)
#define MAX_EXT_CHAR CHAR_INPUT_END
#define EXT_ALPHABET_SIZE (MAX_EXT_CHAR+1)

#endif // GRAPEFRUIT_CONST_H_
